def ex(self, message: str):
    self.exception(message)
